export const tips = [
    "Just a moment... we're training our AI to recognize smiles as a valid ticket.",
    "Did you know our app works in both light and dark mode? Like a vampire's schedule.",
    "Scanning for fun...  just kidding, this is serious business!",
    "Faster than you can find your phone in the dark during the encore.",
    "Firing up the scanner... almost as fast as you'll be checking in guests!",
    "Initializing awesomeness... Prepare to be amazed by our lightning-fast app!",
    "Setting the stage for seamless ticket validation... Your event is about to get even smoother.",
    "Did you know our app has a light/dark mode? Just like your mood swings during concerts.",
    "Getting ready to scan... We're faster than that one friend who always disappears when it's their round.",
    "Warming up the QR code reader... It's about to get hot in here (with valid tickets, of course).",
    "Preparing the ultimate ticket validation experience... This is not a drill!",
    "Loading the future of ticket scanning... Buckle up, it's going to be a smooth ride.",
    "Just a moment... We're making sure your event is as epic as our app.",
    "Powering up... We're about to make ticket validation look easy.",
    "Ticket scanning, optimized... Because nobody likes waiting in line (except maybe that one guy).",
    "We're as excited as you are for this event to start!",
    "Setting the scene for a legendary night... Get ready to scan your way to fun.",
    "We're here to make your event the talk of the town.",
    "Even the QR codes are excited to be scanned by our app.",
    "Preparing to wow you with our speed and simplicity... You won't believe how easy this is."
];
